import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header className="justify-start text-center flex-col flex items-center relative max-w-7xl px-4 md:px-24 lg:px-42 py-8 md:py-12 mx-auto">
      <nav className="flex items-center gap-8">
        <ul className="flex items-center justify-between text-xl gap-8">
          <Link href="/">
            Home
          </Link>
          <Link href="/about">
            About Me
          </Link>
          <Link href="/resume">
            My Resume
          </Link>
        </ul>
      </nav>
    </header>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
